apiVersion: v1
kind: Namespace # Se define un objeto de tipo Namespace
metadata:
  name: tfm-namespace # Se define un nombre para el Namespace

apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio-java
  namespace: tfm-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicio-java
  template:
    metadata:
      labels:
        app: microservicio-java
    spec:
      containers:
      - name: microservicio-java
        image: mopito/tfm:java
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:h2:mem:testdb"
---
apiVersion: v1
kind: Service
metadata:
  name: microservicio-java
  namespace: tfm-namespace
spec:
  selector:
    app: microservicio-java
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
